borrow/urls.py
from django.urls import path
from . import views


app_name = "borrow"
urlpatterns = [
    path('',views.index, name = 'homepage'),
    path('login',views.login_i,name = 'login'),
    path('register',views.register, name = 'register'),
    path('logout',views.logout_i, name = 'logout'),
    path('history',views.AllHistory,name = 'history'),
    path('history/<int:user_id>',views.PersonalHistory,name = 'userprofile'),
    path('detail/<int:record_id>',views.Detail),
]

new_ar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('borrow/',include("borrow.urls",namespace="borrow")),
]

borrow/models.py
#encode :utf-8

from django.db import models
from django.contrib.auth.models import User
# from multiselectfield import MultiSelectField

# Create your models here.
ROOM_LIST ={
        ('FR','301'),
        ('ST','All Boots(ABCD) in 302'),
        ('SA','Boot A in 302'),
        ('SB','Boot B in 302'),
        ('SC','Boot C in 302'),
        ('SD','Boot D in 302'),
    }

STUFF_NAME = {
        ('MC','iMac'), 
        ('DT','Ddesktop'),
        ('PT','Printer'),
        ('SP','Speaker'),
        ('EP','EarPhone'),
    }


s_STUFF_NAME = {
        'iMac', 
        'Ddesktop',
        'Printer',
        'Speaker',
        'EarPhone',
    }

s_ROOM_NAME ={
        '301',
        'All Boots(ABCD) in 302',
        'Boot A in 302',
        'Boot B in 302',
        'Boot C in 302',
        'Boot D in 302',
    }


STATUS_LIST = {
        ('PF','Perfect'),
        ('SB','Slightly Broken'),
        ('TB','Toltally Broken'),
    }

s_STATUS_NAME = {
        'Perfect',
        'Slightly Broken',
        'TB','Toltally Broken',
    }
class Stuff(models.Model):
    spec = models.CharField(max_length = 20,choices = STUFF_NAME)
    status = models.CharField(max_length = 2, choices = STATUS_LIST)
    device_id = models.IntegerField(unique=True)
    is_booked = models.BooleanField(default=False)

    def __str__(self):
        return self.spec + ':' + str(self.device_id)
    
class Room(models.Model):
    spec = models.CharField(max_length = 2,choices = ROOM_LIST)
    is_booked = models.BooleanField(default = False)
    
    def __str__(self):
        return self.spec
    
class BorrowRecord(models.Model):
    StartTime = models.DateTimeField()
    EndTime =  models.DateTimeField()
    # ApplyTime = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)
    is_closed = models.BooleanField(default=False)
    StuffToUse = models.ManyToManyField(Stuff,blank = True, related_name = 'common')
    OtherRequests = models.CharField(default = '无',max_length=100,blank = True)
    # SecretObjects = models.ManyToManyField(Stuff,blank = True,related_name = 'secret')
    RoomToUse = models.ManyToManyField(Room,blank = True)
    borrower= models.ForeignKey(User, on_delete=models.CASCADE)
    ErrorMessage=models.CharField(default=" ",max_length=500,blank = True)

    
class User(User):

    def __str__(self):
        return self.username

borrow/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    school_ID = forms.IntegerField()

    class Meta:
        model = User
        fields = [
            'username',
            'email', 
            'password'
        ]

class BorrowRecordForm(forms.ModelForm):

    class Meta:
        model = BorrowRecord
        fields = [ 
            'StartTime',
            'EndTime',
            'StuffToUse', 
            'OtherRequests',
            'RoomToUse', 
            # 'borrower',
            #is_approved is excluded
        ]

borrow/views.py
# encode:utf-8

from django.shortcuts import render
from django.http import HttpRequest
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse, Http404
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .models import *


ADMIN = ('YangTheBoss','Django','django','TTL')

NameDict = {
    'iMac':'MC',
    'Ddesktop':'DT',
    'Printer':'PT',
    'Speaker':'SP',
    'EarPhone':'EP',
}

RoomDict ={
        '301':'FR',
        'All Boots(ABCD) in 302':'ST',
        'Boot A in 302':'SA',
        'Boot B in 302':'SB',
        'Boot C in 302':'SC',
        'Boot D in 302':'SD',
    }

StatusDict = {
        'Perfect':'PF',
        'Slightly Broken':'SB',
        'Toltally Broken': 'TB',

 }   
# Create your views here.
def index(request):
    # User has to login then view the site
    if not request.user.is_authenticated:
        return HttpResponseRedirect('login')
    else:
        user = request.user

        context = {
            'stuff_type':s_STUFF_NAME,
            'room_type': s_ROOM_NAME,
        }
        stuff = Stuff.objects.all()
        if request.method == 'POST':
            info = request.POST
            print (info)
            starttime = info.__getitem__('StartTime')
            endtime = info.__getitem__('EndTime')
            otherrequests = info.__getitem__('OtherRequests')
            record = BorrowRecord(
                StartTime=starttime,
                EndTime = endtime,
                borrower= request.user,
                OtherRequests = otherrequests,
            )
            record.save()
            for key in info.items():
                if "StuffToUse" in key[0]:
                    # this item is to be added 
                    name = key[1]
                    name=NameDict[name]    
                    remainingstuff = Stuff.objects.filter( spec = name).filter(is_booked=False)
                    require_number = int(key[0][-1])
                    for candidate in info.items():
                        if str(require_number) + "_number" in candidate[0] and len(candidate[1])>0:
                            amount = int(candidate[1])
                            if (amount > remainingstuff.count()):
                                context = {
                                    'wrong_message': "over_quantity",
                                }
                                record.delete()
                                return render(request,'homepage.html',context)
                            else:
                                itemToAdd = remainingstuff[:amount]
                                for target in itemToAdd:
                                    record.StuffToUse.add(target)
                                print("---------------------PASS FOR TEMP")
                if "room" in key[0]:
                    # now it only support one room for 
                    name = key[1]
                    name=RoomDict[name]
                    remainRoom = Room.objects.filter( spec = name).filter(is_booked=False)
                    if remainRoom.count() > 0:
                        for room in remainRoom:
                            record.RoomToUse.add(room)    
        return render(request,'homepage.html',context)

# def BorrowRequest(request, book_id):
#     if not request.user.is_authenticated:
#         return HttpResponseRedirect('borrow/login')
#     else:    
#         user = request.user
#         form = BorrowRecordForm(request.POST or None, request.FILES or None)
#         if form.is_valid(): 
#             record = form.save(commit=False)
#             record.borrower = request.user
#             record.save()
#             return HttpResponseRedirect("/borrow/%d/history" % user.id)
#         context = {
#             "ErrorMessage":"FORM ERROR : FORM UPLOADED IS NOT VALID"
#         }
#         return render(request,'borrow/',context)

def PersonalHistory(request,user_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/borrow/login')
    else:
        if request.user.id != user_id:
            return HttpResponseRedirect('/borrow')
        else:
            requestedLoan = BorrowRecord.objects.filter(borrower=request.user)
            context = {
                'records' : requestedLoan,
            }
            return render(request,'personalhistory.html',context)

def AllHistory(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/borrow')
    else:
        if request.user.username in ADMIN:
            PerformedLoan = BorrowRecord.objects.filter(is_approved = True)
            context1 = {
                'records':PerformedLoan,
            }
            return render(request,'history.html',context=context1)
        return HttpResponseRedirect('/borrow')

"""
Functions related to user authentication
"""
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'homepage.html')
    context = {
        "form": form,
    }
    return render(request, 'register.html', context)

def login_i(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if user.username in ADMIN:
                return HttpResponseRedirect('/borrow')
                # return HttpResponseRedirect('borrow/administration')
            return HttpResponseRedirect('/borrow')
        else :
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')

def logout_i(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        logout(request)
        return render(request, 'login.html')

def Detail(request,record_id):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        record = BorrowRecord.objects.get(id = record_id)
        if not request.user == record.borrower:
            return  HttpResponseRedirect('/borrow')
        else:
            if request.method == 'POST':
                print(request.POST)
                info = request.POST
                if info.__getitem__('choice')== 'status': 
                    item = Stuff.objects.get(id = info.__getitem__('item_id'))
                    new_status = StatusDict[info.__getitem__('NewStatus')]
                    item.status = new_status
                    item.save()
                else:
                    record.is_closed = True
                    record.save()
                    return HttpResponseRedirect('/borrow/history/'+str(record.borrower.id))
            context = {
                'record' : record,
                'status_list' : s_STATUS_NAME,
            }
            return render(request,'detail.html',context)

borrow/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}LoanSystem{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'shelf.png' %}" /> {% comment %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <style>
        #form-container {
            margin: 0px auto;
            width: 1200px;
            /* 必须制定宽度 */
        }
    </style>

</head>


<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <!-- Items -->
            <a class="navbar-brand" href="#">LoanSystem</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item ">
                        <a class="nav-link" href="https://www.ar-lab.cn/">
                            ARlab</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'borrow:homepage' %}">
                            NewRequest
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/borrow/history/{{request.user.id}}">
                            MyRecord
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'borrow:logout'%}">
                            LogOut
                        </a>
                    </li>

                </ul>
            </div>

        </div>
    </nav>
    <br> {% block body %} {% endblock %}
</body>

</html>

borrow/templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}LoanSystem{% endblock %}</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{%  static 'shelf.png' %}" /> 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>


  <style>
    #form-container {
      margin: 0px auto;
      width: 1200px;
      /* 必须制定宽度 */
    }
  </style>

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">LoanSystem</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'borrow:register'%}">注册</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'borrow:login'%}">登录</a>
        </li>

      </ul>

    </div>
  </nav>
  {% block body %} {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

borrow/templates/homepage.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en" class="gr__v4_bootcss_com">
{% block body %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    {%load static%}
    <link href="{% static 'Checkout example for Bootstrap_files/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        var count = 1; 
        $('#bt-add').click(function () {
            count += 1 ;
            var select_name = "StuffToUse" + count;
            var select_id = "id" + select_name;
            var number_name = count + "_number";
            var number_id = "id" + number_name;
            console.log('fuck')
            $("#pa-c").append(
                "<br></br><div class = \"form-group\"><select id=\""+ select_id + "\" name = \"" + select_name + "\"class= \"custom-select d-block witems-100\" >>{% for item in stuff_type %}<option>{{item}}</option>{%endfor%}</select></div>\
                <div><label>数量</label><input  name = \""+number_name+ "\"class = \"form-control\" type = \"number\"></div>"
            )
            
        })
    })
</script>

<body class="bg-light" data-gr-c-s-loaded="true">

    <div class="container">

        <form id="requestform" class="needs-validation" role="form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <div id="pa-c">
                    <div class="mb-3">
                        <label for="count">Available Item</label>
                        <select class="custom-select d-block witems-100" id="id_StuffToUse0" name="StuffToUse0">
                            <option value="">Choose...</option>
                            {% for item in stuff_type %}
                            <option>{{item}}</option>> {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label>Quantity</label>
                        <input type = "number" class = "form-control" name = "0_number">
                    </div>
                </div>
                <br></br>
                <input id='bt-add' type='button' class="btn btn-primary" value="Borrow Another One">
                <br></br>
            </div>

            <div class="form-group">
                <div class="mb-3">
                    <label for="address">OtherRequests</label>
                    <input name="OtherRequests" id="id_OtherRequests" type="text" class="form-control" placeholder="无" id="item2">
                </div>
            </div>

            <div class="container">
                <fieldset>
                    <div class="form-group">
                        <label for="dtp_input1" class="col-md-2 control-label">StartTime</label>
                        <div class="input-group date form_datetime col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="yyyy-mm-dd hh:ii:ss"
                            data-link-field="dtp_input1">
                            <input class="form-control" size="16" type="text" value="" name="StartTime" id="id_StarTime" readonly required>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-remove"></span>
                            </span>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </span>
                        </div>
                        <input type="hidden" id="dtp_input1" value="" />
                        <br/>
                    </div>
                    <div class="form-group">
                        <label for="dtp_input1" class="col-md-2 control-label">EndTime</label>
                        <div class="input-group date form_datetime col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="yyyy-mm-dd hh:ii:ss"
                            data-link-field="dtp_input1">
                            <input class="form-control" size="16" type="text" value="" name='EndTime' id="id_EndTime" readonly required>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-remove"></span>
                            </span>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </span>
                        </div>
                        <input type="hidden" id="dtp_input1" value="" />
                        <br/>
                    </div>
                </fieldset>

            </div>
            <div class="form-group">
                <div class="mb-3">
                    <label for="count">Available Rooms</label>
                    <select class="custom-select d-block w-100" id="id_room" name="room">
                        <option value="">Choose</option>
                        {%for room in room_type%}
                        <option>{{room}}</option>
                        {%endfor%}
                    </select>
                </div>
            </div>


            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>


        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">AR-lab</p>
        </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {%load static%}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'jquery/jquery-1.8.3.min.js' %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js'%}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static 'js/locales/bootstrap-datetimepicker.fr.js'%}" charset="UTF-8"></script>
    <script type="text/javascript">
        $('.form_datetime').datetimepicker({
            //language:  'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            showMeridian: 1
        });
        $('.form_date').datetimepicker({
            language: 'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0
        });
        $('.form_time').datetimepicker({
            language: 'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 1,
            minView: 0,
            maxView: 1,
            forceParse: 0
        });
    </script>

    <span id="sbmarwbthv5"></span>
{% endblock %}

</body>

</html>

borrow/templates/login.html
{% extends 'base_visitor.html' %}
{% block title %}登录{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid" id = 'form-container'>

        <div class="col-sm-12 col-md-6" id = 'form-container'>
                <div class="panel-body" >
                        <br /><br />
                        <h2>登入已有账号</h2>
                        <br /><br />
                    {% if error_message %}
                    <div class="alert alert-warning" role="alert">
                            <strong>Warning!</strong>{{error_message}}
                          </div>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'borrow:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                用户名
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" class="form-control" maxlength="30" name="username" type="text" placeholder=" 输入用户名" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                密码
                            </label>
                            <div class="col-sm-10">
                                <input class = "form-control" id="id_password" maxlength="30" name="password" type="password" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit"  class="btn btn-primary">登录</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    还没有账号？ <a href="{% url 'borrow:register' %}">点这里</a> 注册一个
                </div>
        </div>

</div>

{% endblock %}

borrow/templates/register.html
{% extends 'base_visitor.html' %}
{% block title %}注册{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid" id = 'form-container'>

        <div class="col-sm-12 col-md-6" id = 'form-container'>
            <div class="panel panel-default">
                <div class="panel-body">
                    <br /><br />
                    <h2>注册一个新的账号</h2>
                    <br /><br />
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small"></span>
                                </div>
                                <label class="control-label col-sm-2" for="song_title"><label for="id_username">用户名</label></label>
                                <div class="col-sm-10"><input class = "form-control" type="text" name="username" required id="id_username" maxlength="150" /></div>
                            </div>
                        
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small"></span>
                                </div>
                                <label class="control-label col-sm-2" for="song_title"><label for="id_email">邮箱</label></label>
                                <div class="col-sm-10"><input class = "form-control" type="email" name="email" id="id_email" maxlength="254" /></div>
                            </div>
                        
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small"></span>
                                </div>
                                <label class="control-label col-sm-2" for="song_title"><label for="id_password">密码</label></label>
                                <div class="col-sm-10"><input class = "form-control" type="password" name="password" required id="id_password" /></div>
                            </div>
                        
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small"></span>
                                </div>
                                <label class="control-label col-sm-2" for="song_title"><label for="id_school_ID">学工号</label></label>
                                <div class="col-sm-10"><input class = "form-control" type="number" name="school_ID" required id="id_school_ID" /></div>
                            </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">注册</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    已经有一个账号了? <a href="{% url 'borrow:login' %}">点这里</a>登录.
                </div>
            </div>
        </div>

</div>

{% endblock %}